chmod a=rwx vehicles
chmod a=rwx vehicles/public_bicycles
chmod a=rwx vehicles/public_cars
chmod a=rwx vehicles/public_planes
chmod go-rw vehicles/bicycles
chmod go-rw vehicles/planes
chmod go-rw vehicles/cars
chmod a+x vehicles/bicycles
chmod a+x vehicles/planes
chmod a+x vehicles/cars
